spring:
  application:
    name: "Veterinary"

  datasource:
    url: jdbc:postgresql://localhost:5432/veterinary_management
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop